################################################################
##  Spatial-Functional Mixture Models: Regionalization of BTH ##
##  Outputs: Figures 2, 7, 8, and 10 of the manuscript.       ##
################################################################
rm(list=ls())

#####################################################
##  Load associated required packages
library(fda)
library(zoo)
library(ggmap) 
library(scales)


######################################################
##  Source files for the algorithm functions 
source('../functions.R')
source('regionalize_BTH.R')

##################################################################
##  Read data

station0 = read.csv('../../data/station_location_BTH.csv',
                    sep=',',fileEncoding  = 'GBK')

station = station0[,c('lon','lat')]
station = station[-52,]  ## remove a background station

curve.num = nrow(station)

dd = read.csv('../../data/BTH_PM25_monthly.csv')
dd = dd[,-(1:2)]
dd = dd[,-52]
data = as.matrix(dd[6:48,])
day = dim(data)[1]

log.data = log(data)

##########################################
##  neighbor selected by KNN
knn = 5

dist = as.matrix(dist(station))
dist.ord = apply(dist,2,order)
dist.order = t(dist.ord)
nb = dist.order[,2:(knn+1)]

y.neigh = list()
for(i in 1:curve.num){
  y.neigh[[i]] = nb[i,]
}   

############################################
##  regionalization   

cluster.num = 3

fit.BTH = regionalize_BTH( log.data, cluster.num, neighbor = y.neigh, P = 12)

cluster = fit.BTH$cluster


##################################################################
## Reproduce Figure 4 and Figure 5 in the manuscript
##################################################################

#-----------------------------------------------------------------
# Figure 7: 
# Regionalization map of BTH
#-----------------------------------------------------------------


load('../../data/BTH_map.Rdata')
## which was generated by 
## map1 = get_map(location = c(lon = 116.9, lat = 38.7), zoom = 7, scale=2, color='bw')
## save(map1,file='BTH_map.Rdata')


region = as.factor(cluster)

region_label = c("South","North","Middle")
region_level = c("Middle","North","South")
region_func <- function(i){ region_label[as.numeric(i)] }

out_clustermap = data.frame(lon=station$lon,lat=station$lat,
                            region=factor(region_func(cluster),levels=region_level) )

plot_clustermap <- 
  ggmap(map1) +
  theme(legend.position = "bottom", 
        legend.title = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank() ) +
  geom_point(data = out_clustermap,
             aes(lon,lat,colour = region),
             size=2) +
  scale_y_continuous( limits = c(36.35, 41.15) ) +
  scale_color_discrete( breaks = c('North','Middle','South') )

plot_clustermap 
ggsave(filename = paste('RealData_BTHClusterMap_',cluster.num,'.pdf',sep=""),
       height = 6,
       width = 6)

#-----------------------------------------------------------------
# Figure 8: 
# Estimated mean functions of BTH
#-----------------------------------------------------------------

date = seq(as.Date("2013-06-01"), as.Date("2016-12-31"), by="1 month")

mean.clustered = matrix(NA,day,cluster.num)
mean.region = matrix(NA,day,cluster.num)
for(i in 1:cluster.num){
  mean.clustered[,i] = fit.BTH$muhat[[i]] 
  mean.region[,i] = rep(i,day)
}
mean.est = data.frame(t = rep(1:day,cluster.num), 
                      date = date,
                      y = as.vector(mean.clustered),
                      region = factor(region_func(as.vector(mean.region)),levels=region_level) )

plot_mean <-
  ggplot()+
  theme(legend.position = "bottom", 
        legend.title = element_blank() ) +
  geom_line(data=mean.est,
            aes(x=date,y=y,colour=region),
            size=1) +
  ylab("Estimated Mean Functions") +
  xlab("Time") +
  scale_x_date( date_labels = "%Y/%m", breaks=date_breaks("6 month")) +
  scale_color_discrete( breaks = c('North','Middle','South') )

plot_mean
ggsave(filename = paste('RealData_BTHEstimatedMean_',cluster.num,'.pdf',sep=""), 
       height = 4,
       width = 9)   



#-----------------------------------------------------------------
# Figure 9: 
# Estimated global and regional mean functions
#-----------------------------------------------------------------

mu0 = apply(mean.clustered,1,mean)
mu0.est = data.frame(   date = date, y = as.vector(mu0) )

plot_globalmean <-
  ggplot()+
  theme(legend.position = "bottom", 
        legend.title = element_blank()
  ) +
  geom_line(data = mu0.est,
            aes(x=date,y=y),
            size = 1) +
  ylab("Glaobal Mean Function") +
  xlab("") +
  ylim(c(3.5,5)) +
  scale_x_date( date_labels = "%Y/%m", breaks=date_breaks("6 month")) 

plot_globalmean  ## global mean function
ggsave(filename = 'RealData_BTHDemean_globalmean.png', 
       height = 2,
       width = 8)   

demean.clustered = mean.clustered - mu0
demean.est = data.frame(t = rep(1:day,cluster.num),
                        date = date,
                        y = as.vector(demean.clustered),
                        region = factor(region_func(as.vector(mean.region)),levels=region_level) )

plot_demean <-
  ggplot()+
  theme(legend.position = "bottom", 
        legend.title = element_blank() ) +
  geom_line(data=demean.est,
            aes(x=date,y=y,colour=region),
            size=1) +
  ylab("Regional Mean Functions") +
  xlab("Time") +
  scale_x_date( date_labels = "%Y/%m", breaks=date_breaks("6 month")) +
  scale_color_discrete( breaks = c('North','Middle','South') )

plot_demean  ## regiona mean functions
ggsave(filename = 'RealData_BTHDemean_regionalmean.png', 
       height = 4,
       width = 8)   



#-----------------------------------------------------------------
# Figure 2: 
# Location maps of BTH
#-----------------------------------------------------------------

library(rgdal)
library(plyr)
library(ggmap)

mapdata = readOGR('../../data/BTH_boundary/dishi84.shp')
mapdata_BTH <- mapdata[mapdata$NAME == '北京市'|mapdata$NAME == '天津市'|
                         mapdata$NAME == '廊坊市'|mapdata$NAME == '保定市'|
                         mapdata$NAME == '唐山市'|mapdata$NAME == "承德市"|
                         mapdata$NAME == '张家口市'|mapdata$NAME== '沧州市'|
                         mapdata$NAME == '秦皇岛市'|mapdata$NAME == '石家庄市'|
                         mapdata$NAME== '衡水市'|mapdata$NAME == '邢台市'|
                         mapdata$NAME == '邯郸市',]
mapmat_BTH <- fortify(mapdata_BTH)

load('../../data/BTH_boundary/BTH_boundary.Rdata')
## which was generated by 
## map2 = get_map(location = c(lon = 116.9, lat = 38.7),maptype="terrain",zoom = 6)
## save(map2,file='BTH_boundary.Rdata')

plot_stationmap <-
  ggmap(map2) +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank() ) +
  geom_point(data = station,
             aes(lon,lat),
             colour = 'red',
             size=1) +
  geom_polygon(data = mapmat_BTH,
               aes(x = long,y = lat, group = group),
               colour = 'black',
               fill = NA) +
  scale_x_continuous(limits = c(113, 120)) +
  scale_y_continuous(limits = c(35.9, 42.8))

plot_stationmap
ggsave(filename = 'BTHStationMap.png',
       height = 8,
       width = 6)   

## This produced figure may look slightly different from Figure 2 that is identical to 
## Figure S1 in the supplementary materials of Chen et al. (2018).
## The difference is due to a resolution issue. 
## The authors clarified with the authors of Chen et al. (2018) who confirmed that 
## Figure S1 was produced by merging four figures with very high resolutions (zoom = 7) using some drawing software. 


